import type { Rating } from '../../../core/interface/rating.interface';

export type RatingColumnType = 'text' | 'status';

export interface RatingColumn {
  key: keyof Rating;
  label: string;
  type?: RatingColumnType;
}

export const RATING_TABLE_COLUMNS: RatingColumn[] = [
  { key: 'QuoteID', label: 'Quote ID' },
  { key: 'PolicyID', label: 'Policy ID' },
  { key: 'Accountlocid', label: 'AccountLocID' },
  { key: 'SubmissionLocID', label: 'Submission Loc ID' },
  { key: 'GLStatus', label: 'GL Status', type: 'status' },
  { key: 'EffectiveDate', label: 'Effective Date' },
  { key: 'ExpirationDate', label: 'Expiration Date' },
  { key: 'CancellationDate', label: 'Cancellation Date' },
  { key: 'ProRateFactor', label: 'ProRate Factor' },
  { key: 'EntityName', label: 'Entity' },
  { key: 'Address', label: 'Address' },
  { key: 'City', label: 'City' },
  { key: 'State', label: 'State' },
  { key: 'ZIP', label: 'Zip' },
  { key: 'County', label: 'County' },
  { key: 'ISOTerritory', label: 'ISO Territory' },
  { key: 'primary_classcode', label: 'Primary Class Code' },
  { key: 'primary_exposurebasis', label: 'Primary Exposure Basis' },
  { key: 'primary_exposurevalue', label: 'Primary Exposure' },
  { key: 'secondary_classcode', label: 'Secondary Class Code' },
  { key: 'secondary_exposurebasis', label: 'Secondary Exposure Basis' },
  { key: 'secondary_exposurevalue', label: 'Secondary Exposure' },
  { key: 'tertiary_classcode', label: 'Tertiary Class Code' },
  { key: 'tertiary_exposurebasis', label: 'Tertiary Exposure Basis' },
  { key: 'tertiary_exposurevalue', label: 'Tertiary Exposure' },
  { key: 'OccuranceLimitAggregateLimit', label: 'OCC/AGG Limit' },
  { key: 'Deductible', label: 'Deductible' },
  { key: 'NumBeaches', label: '# Beaches' },
  { key: 'AcresPark', label: '# Acres Parks' },
  { key: 'Pools', label: '# of Pools' },
  { key: 'WaiverOfSubrogation', label: 'WOS' },
  { key: 'PrimaryAndNoncontributory', label: 'PNC' },
  { key: 'BlanketAdditionalInsured', label: 'BAI' },
  { key: 'HiredAndNonownedAuto', label: 'HNOA' },
  { key: 'AssultAndBatterySubLimit', label: 'A&B Sub-limit' },
  { key: 'HabitationSubLimit', label: 'Hab Sub-Limit' },
  { key: 'primary_parking_classcode', label: 'Primary Parking Class Code' },
  { key: 'primary_parking_exposurebasis', label: 'Primary Parking Exposure Basis' },
  { key: 'primary_parking_exposure', label: 'Primary Parking Exposure' },
  { key: 'secondary_parking_classcode', label: 'Secondary Parking Class Code' },
  { key: 'secondary_parking_exposurebasis', label: 'Secondary Parking Exposure Basis' },
  { key: 'secondary_parking_exposure', label: 'Secondary Parking Exposure' },
  { key: 'tertiary_parking_classcode', label: 'Tertiary Parking Class Code' },
  { key: 'tertiary_parking_exposurebasis', label: 'Tertiary Parking Exposure Basis' },
  { key: 'tertiary_parking_exposure', label: 'Tertiary Parking Exposure' },
  { key: 'primary_Parking_PremiumOpsBaseRate', label: 'Primary Parking Prem/Ops Base Rate' },
  { key: 'secondary_Parking_PremiumOpsBaseRate', label: 'Secondary Parking Prem/Ops Base Rate' },
  { key: 'tertiary_Parking_PremiumOpsBaseRate', label: 'Tertiary Parking Prem/Ops Base Rate' },
  { key: 'lcm', label: 'LCM' },
  { key: 'ilf', label: 'ILF' },
  { key: 'Primary_PremiumOpsBaseRate', label: 'Primary Premium/Ops Base Rate' },
  { key: 'secondary_PremiumOpsBaseRate', label: 'Secondary Premium/Ops Base Rate' },
  { key: 'tertiary_PremiumOpsBaseRate', label: 'Tertiary Premium/Ops Base Rate' },
  { key: 'DeductibleFactor', label: 'Deductible Factor' },
  { key: 'IRPMDebit/Credit', label: 'IRPM Debit/Credit' },
  { key: 'TierFactor', label: 'Tier Factor' },
  { key: 'SubTotalGLBaseAnnualPremium', label: 'Sub-Total GL Base Annual Premium' },
  { key: 'BeachAnnualPremium', label: 'Beach Annual Premium' },
  { key: 'ParksAnnualPremium', label: 'Parks Annual Premium' },
  { key: 'SwimmingPoolAnnualPremium', label: 'Swimming Pool Annual Premium' },
  { key: 'ParkingAnnualPremium', label: 'Parking Annual Premium' },
  { key: 'SubTotalPolicyAnnualPremium', label: 'Sub-Total Policy Annual' },
  { key: 'AandBAnnualPremium', label: 'A&B Annual Premium' },
  { key: 'HabAnnualPremium', label: 'Hab Annual Premium' },
  { key: 'WOSPremium', label: 'WOS Annual Premium' },
  { key: 'PNCAnnualPremium', label: 'PNC Annual Premium' },
  { key: 'BlanketAIAnnualPremium', label: 'Blanket AI Annual Premium' },
  { key: 'HONAAnnualPremium', label: 'HNOA Annual Premium' },
  { key: 'TotalGL_Premium', label: 'Total GL Annual Premium' },
  { key: 'MinAnnualPremium', label: 'Min Annual Premium' },
  { key: 'Final_Gl_Premium', label: 'Final GL Annual Premium' },
  { key: 'SubTotalPolicyProratedPremium', label: 'Sub Total Policy Prorated Premium' },
  { key: 'AandBProratedPremium', label: 'A & B Prorated Premium' },
  { key: 'HabProratedPremium', label: 'Hab. Prorated Premium' },
  { key: 'WOSProratedPremium', label: 'WOS Prorated Premium' },
  { key: 'PNCProratedPremium', label: 'PNC Prorated Premium' },
  { key: 'BlanketAIProratedPremium', label: 'Blanket AI Prorated Premium' },
  { key: 'HONAProratedPremium', label: 'HNOA Prorated Premium' },
  { key: 'ProratedARMFee', label: 'Prorated Arm Fee' },
  { key: 'ProratedPolicyTotal', label: 'Prorated Policy Total' },
  { key: 'Prorated_SL_Stampingfee', label: 'Prorated SL Stamping Fee' },
  { key: 'Prorated_SL_Tax', label: 'Prorated SL Tax' },
  { key: 'Prorated_SL_Otherfee', label: 'Prorated SL Other Fee' },
  { key: 'ProratedARMInspectionFee', label: 'Prorated ARM Inspection Fee' },
  { key: 'Final_Policy_Total', label: 'Final Policy Total' },
];