export interface GlMasterPolicy {
  GeneralLiabilityId: string;
  AccountID: number;
  QuoteID: string;
  GLStatus: string;
  PolicyID: string | null;
  Accountlocid: number;
  SubmissionLocID: number;
  QuoteVersion: number;
  LatestVersion: boolean;
  SelectedVersion: boolean;
  RatingPeriodName: string;
  RatingPeriodID: number;
  PolicyStatus: string;
  PolicyType: string;
  PlanEffectiveDate: string;
  PlanExpirationDate: string;
  ProRateFactor: number;
  EndorsementEffectiveDate: string | null;
  EndorsementExpirationDate: string | null;
  EndorsementType: string | null;
  EndorsePlanEffectiveDate: string;
  AccountName: string;
  EntityName: string;
  MainAddress: string;
  City: string;
  StateCode: string;
  ZipCode: string;
  OrigBuildYear: number;
  Buildings: number;
  Stories: number;
  HabUnits: number;
  ConstructionISO: string;
  SprinklerText: string;
  WiringType: string;
  CommSqFt: number;
  HabSqFt: number;
  ParkingSqFt: number;
  TotalSqFt: number;
  PropertyType: string;
  OccupancyNotes: string | null;
  PercOccupied: number;
  PercSubsidized: number;
  PercStudent: number;
  PercAssistedLiving: number;
  County: string;
  Pools: number;
  Playgrounds: number;
  CourtsGyms: number;
  OccuranceLimitAggregateLimit: string;
  Deductible: number;
  WaiverOfSubrogation: boolean;
  PrimaryAndNoncontributory: boolean;
  BlanketAdditionalInsured: boolean;
  HiredAndNonownedAuto: boolean;
  AssultAndBatterySubLimit: string;
  HabitationSubLimit: string;
  FireAlarmCentralOrLocal: string;
  CommonAreasAdequateLighting: boolean;
  DrivewaysParkingCommonAreaInGoodCondition: boolean;
  EmergencyExitSigns: boolean;
  FormalSafetyDisasterPlan: boolean;
  FormalEmployeeTrainingProgram: boolean;
  FormalMaintenanceSafetyOrderTracking: boolean;
  FormalSafetyProgram: boolean;
  SafetyEquipmentUnder10Years: boolean;
  PetRestrictionText: string;
  SecurityCamerasCoverage: boolean;
  SmokeDetectorsInAllUnits: boolean;
  Walkwayscondition: boolean;
  primary_operation: string | null;
  primary_classcode: number | null;
  primary_exposurebasis: string | null;
  primary_exposurevalue: number | null;
  secondary_operation: string | null;
  secondary_classcode: number | null;
  secondary_exposurebasis: string | null;
  secondary_exposurevalue: number | null;
  tertiary_operation: string | null;
  tertiary_classcode: number | null;
  tertiary_exposurebasis: string | null;
  tertiary_exposurevalue: number | null;
  primary_parking_type: string | null;
  primary_parking_classcode: number | null;
  primary_parking_exposurebasis: string | null;
  primary_parking_exposure: number | null;
  secondary_parking_type: string | null;
  secondary_parking_classcode: number | null;
  secondary_parking_exposurebasis: string | null;
  secondary_parking_exposure: number | null;
  tertiary_parking_type: string | null;
  tertiary_parking_classcode: number | null;
  tertiary_parking_exposurebasis: string | null;
  tertiary_parking_exposure: number | null;
  isGLSecondaryRatingRequired: boolean;
  isGLtertiaryRatingRequired: boolean;
  LossRunYears: number;
  TotalLosses: number;
  vcPropertyPremAdjusted: number;
  TargetAnnualPremium: number;
  MailAddress: string | null;
  MailCity: string | null;
  MailStateCode: string | null;
  MailZipCode: string | null;
  ScheduleID: number;
  GLSchedulesId: string;
  ActiveCancelFactor: number;
  CancellationDate: string | null;
  EndorsementDescription: string | null;
  MurderScore: string;
  AggravatedAssaultScore: string;
  RobberyScore: string;
  PropertyCrimeScore: string;
  MotorVehicleTheftScore: string;
  RapeScore: string;
  BurglaryScore: string;
  OverallTotalCrimeScore: string;
  LatestEndorsementRow: string;
  ProbabilityOfDefaultPercent: number | null;
  ImpliedRating: string | null;
  ConservativeCreditLimitUSD: number | null;
  BalancedCreditLimitUSD: number | null;
  AggressiveCreditLimitUSD: number | null;
  PaymentDelinquencyRiskScoreLastMonth: number | null;
  PaymentDelinquencyRiskScoreLabelLastMonth: string | null;
  PaymentRiskScoreValueLastMonth: number | null;
  PaymentRiskScoreLabelLastMonth: string | null;
  PaymentRiskSegmentLastMonth: string | null;
  PaymentRiskLabelLastMonth: string | null;
  LongTermHealthLabelLastMonth: string | null;
  CreditRiskRatingCategoryLastMonth: string | null;
  CreditRiskRatingLabelLastMonth: string | null;
  NAICS2022PrimaryCode: string | null;
  NAICS2022PrimaryCodeDescription: string | null;
  BvDIDNumber: string | null;
  OrbisIDNumber: string | null;
  NationalID: string | null;
  IsPolicyGenerated: boolean;
  Location_Description: string | null;
  Location_Address: string | null;
}

export interface GlMasterPoliciesResponse {
  isSuccess: boolean;
  responseMsg: string;
  data: GlMasterPolicy[];
  serverDateTime: number;
}
