export interface Rating {
  AccountID: number;
  RatingPeriodID: number;
  RatingPeriodName: string;
  GeneralLiabilityId: string;
  QuoteID: string;
  PolicyID: string | null;
  PolicyType: string;
  PolicyStatus: string;
  Accountlocid: number;
  SubmissionLocID: number;
  GLStatus: string;
  ClassCode: number;
  EffectiveDate: string;
  ExpirationDate: string;
  CancellationDate: string | null;
  ProRateFactor: number;
  EntityName: string;
  Address: string;
  City: string;
  State: string;
  ZIP: string;
  County: string;
  ISOTerritory: string;
  Operation: string | null;
  ExposureBasis: string | null;
  Exposurevalue: number | null;
  primary_classcode: number;
  primary_exposurebasis: string | null;
  primary_exposurevalue: number;
  secondary_classcode: number | null;
  secondary_exposurebasis: string | null;
  secondary_exposurevalue: number;
  tertiary_classcode: number | null;
  tertiary_exposurebasis: string | null;
  tertiary_exposurevalue: number;
  OccuranceLimitAggregateLimit: string;
  Deductible: number;
  NumBeaches: number;
  AcresPark: number;
  Pools: number;
  WaiverOfSubrogation: boolean;
  PrimaryAndNoncontributory: boolean;
  BlanketAdditionalInsured: boolean;
  HiredAndNonownedAuto: boolean;
  AssultAndBatterySubLimit: string;
  HabitationSubLimit: string;
  ParkingType: string | null;
  ParkingExposure: string | null;
  primary_parking_classcode: number | null;
  primary_parking_exposurebasis: string | null;
  primary_parking_exposure: number;
  secondary_parking_classcode: number | null;
  secondary_parking_exposurebasis: string | null;
  secondary_parking_exposure: number;
  tertiary_parking_classcode: number | null;
  tertiary_parking_exposurebasis: string | null;
  tertiary_parking_exposure: number;
  primary_Parking_PremiumOpsBaseRate: number;
  secondary_Parking_PremiumOpsBaseRate: number;
  tertiary_Parking_PremiumOpsBaseRate: number;
  lcm: number;
  ilf: number;
  Primary_PremiumOpsBaseRate: number;
  secondary_PremiumOpsBaseRate: number;
  tertiary_PremiumOpsBaseRate: number;
  DeductibleFactor: number;
  'IRPMDebit/Credit': number;
  TierFactor: number;
  SubTotalGLBaseAnnualPremium: number;
  BeachAnnualPremium: number;
  ParksAnnualPremium: number;
  SwimmingPoolAnnualPremium: number;
  ParkingAnnualPremium: number;
  Primary_ParkingAnnualPremium: number;
  Secondary_ParkingAnnualPremium: number;
  Tertiary_ParkingAnnualPremium: number;
  SubTotalPolicyAnnualPremium: number;
  AandBAnnualPremium: number;
  HabAnnualPremium: number;
  WOSPremium: number | null;
  PNCAnnualPremium: number | null;
  BlanketAIAnnualPremium: number | null;
  HONAAnnualPremium: number | null;
  TotalGL_Premium: number | null;
  MinAnnualPremium: number;
  SubFinalGLAnnualPremium: number | null;
  ARMFee: number | null;
  Final_Gl_Premium: number | null;
  AnnualSLStampingFee: number | null;
  AnnualSLTax: number | null;
  AnnualSLOtherFee: number | null;
  AnnualInspectionARMFee: number;
  AnnualPolicyTotal: number | null;
  Prorated_Annual_Premium: number;
  Prorated_Brokerfee: number;
  Prorated_ARMfee: number;
  Prorated_Broker_ARM_fee: number;
  Prorated_Inspectionfee: number;
  isGLSecondaryRatingRequired: boolean;
  isGLtertiaryRatingRequired: boolean;
  Primary_operation_premium: number;
  Secondary_operation_premium: number;
  Tertiary_operation_premium: number;
  LatestVersion: boolean;
  SelectedVersion: boolean;
  QuoteVersion: number;
  primary_operation: string;
  secondary_operation: string | null;
  tertiary_operation: string | null;
  primary_parking_type: string | null;
  secondary_parking_type: string | null;
  tertiary_parking_type: string | null;
  MailAddress: string | null;
  MailCity: string | null;
  MailStateCode: string | null;
  MailZipCode: string | null;
  ActiveCancelFactor: number;
  CancellationType: string | null;
  HNOA_Coverage: number;
  ScheduleId: number;
  LatestEndorsementRow: string;
  SubTotalPolicyProratedPremium: number;
  WOSProratedPremium: number | null;
  PNCProratedPremium: number | null;
  BlanketAIProratedPremium: number | null;
  HONAProratedPremium: number | null;
  SubProratedAnnualPremium: number;
  ProratedARMFee: number;
  ProratedPolicyTotal: number;
  Prorated_SL_Stampingfee: number;
  Prorated_SL_Tax: number;
  Prorated_SL_Otherfee: number;
  ProratedARMInspectionFee: number;
  Final_Policy_Total: number;
  AandBProratedPremium: number;
  HabProratedPremium: number;
  TotalGLProratedPremium: number;
  primary_exposurevalue1: number;
  secondary_exposurevalue1: number;
  tertiary_exposurevalue1: number;
  primary_parking_exposure1: number;
  secondary_parking_exposure1: number;
  tertiary_parking_exposure1: number;
  Debug_IsCancelFromFirstBoundOnly: boolean;
  Debug_IsCancelFromFirstBoundABHabOnly: boolean;
  Debug_FirstEndorsementScheduleId: number | null;
  Debug_PriorEndorsementScheduleCount: number | null;
  Debug_CancelBranch: string;
  Debug_BAIHNOA_ProRateFactor: number;
  Debug_BAIHNOA_DaysFirstBoundPeriod: number | null;
  Debug_BAIHNOA_FirstBoundProrateBasis: number | null;
  Debug_BAIHNOA_BAIProrated: number | null;
  Debug_BAIHNOA_HNOAProrated: number | null;
  Debug_BAIHNOA_EarnedFactor: number | null;
}

export interface RatingResponse {
  isSuccess: boolean;
  responseMsg: string;
  data: Rating[];
  serverDateTime: number;
}