export interface UnderwritingReview {
  AccountID: number;
  RatingPeriodID: number;
  GeneralLiabilityId: string;
  QuoteID: string;
  PolicyID: string | null;
  AccountLocID: number;
  SubmissionLocID: number;
  QuoteVersion: number;
  LatestVersion: boolean;
  SelectedVersion: boolean;
  GLStatus: string;
  ClassCode: number;
  EffectiveDate: string;
  ExpirationDate: string;
  CancellationDate: string | null;
  ProRateFactor: number;
  EntityName: string;
  Address: string;
  City: string;
  State: string;
  ZIP: string;
  County: string;
  '5YearLossTotal': number;
  ZipFireScore: number | null;
  LocationFireScore: number | null;
  ZipCrimeScore: number | null;
  LocationCrimeScore: number | null;
  ZipHomicideScore: number | null;
  LocationHomicideScore: number | null;
  'ZIPA&BScore': number | null;
  'LocationA&BScore': number | null;
  ZipBurgleryScore: number | null;
  LocationBrugleryScore: number | null;
  ZipRapeScore: number | null;
  LocationRapeScore: number | null;
  OFACFlag: string | null;
  LocationRiskScore: number | null;
  OwnerRiskScore: number | null;
  FireAlarmType: string;
  CommonAreasLighting: boolean;
  Drivewayscondition: boolean;
  EmergencyExitSignes: boolean;
  FormalSafetyDisasterPlan: boolean;
  FormalEmployeeTrainingProgram: boolean;
  FormalMaintenancetracking: boolean;
  SafetyEquipmentunder10yrs: boolean;
  Petsrestrictions: string;
  IsSecurityCamerasavailable: boolean;
  IsSmokeDetectorsavailable: boolean;
  Walkwayscondition: boolean;
  IRPMLocationInsideNotes: string | null;
  IRPMLocationOutsideNotes: string | null;
  IRPMPremisesNotes: string | null;
  IRPMEquipmentNotes: string | null;
  IRPMClassificationNotes: string | null;
  IRPMEmployeesNotes: string | null;
  IRPMCooperationNotes: string | null;
  IRPMLocationInsideDebitCredit: number | null;
  IRPMLocationOutsideDebitCredit: number | null;
  IRPMPremisesDebitCredit: number | null;
  IRPMEquipmentDebitCredit: number | null;
  IRPMClassificationDebitCredit: number | null;
  IRPMEmployeesDebitCredit: number | null;
  IRPMCooperationDebitCredit: number | null;
  FinalIRPMCreditDebit: number;
  TierBuildingAgeNotes: string | null;
  TierPremisesSafetyNotes: string | null;
  TierLocationNotes: string | null;
  TierFactor: number;
  GLSchedulesId: string;
  IRPMLocationCombinedDebitCredit: number | null;
  primary_classcode: number;
  secondary_classcode: number | null;
  tertiary_classcode: number | null;
  Description_of_Business: string | null;
  Location_Description: string | null;
  ScheduleId: number;
  MurderScore: number | null;
  AggravatedAssaultScore: number | null;
  RobberyScore: number | null;
  PropertyCrimeScore: number | null;
  MotorVehicleTheftScore: number | null;
  RapeScore: number | null;
  BurglaryScore: number | null;
  OverallTotalCrimeScore: number | null;
  ProbabilityOfDefaultPercent: number | null;
  ImpliedRating: string | null;
  ConservativeCreditLimitUSD: number | null;
  BalancedCreditLimitUSD: number | null;
  AggressiveCreditLimitUSD: number | null;
  PaymentDelinquencyRiskScoreLastMonth: number | null;
  PaymentDelinquencyRiskScoreLabelLastMonth: string | null;
  PaymentRiskScoreValueLastMonth: number | null;
  PaymentRiskScoreLabelLastMonth: string | null;
  PaymentRiskSegmentLastMonth: string | null;
  PaymentRiskLabelLastMonth: string | null;
  LongTermHealthLabelLastMonth: string | null;
  CreditRiskRatingCategoryLastMonth: string | null;
  CreditRiskRatingLabelLastMonth: string | null;
  NAICS2022PrimaryCode: string | null;
  NAICS2022PrimaryCodeDescription: string | null;
  BvDIDNumber: string | null;
  OrbisIDNumber: string | null;
  MinimumRoofConditionRating: string | null;
  LotDebris: string | null;
  LotDebrisCoveragePercentage: number | null;
  ParkingLot: string | null;
  ParkingLotPavedArea: string | null;
  ParkingLotIllumination: string | null;
  ParkingLotDeterioration: string | null;
  NationalID: string | null;
  IsPolicyGenerated: boolean;
  Location_Address: string | null;
}

export interface UnderwritingReviewResponse {
  isSuccess: boolean;
  responseMsg: string;
  data: UnderwritingReview[];
  serverDateTime: number;
}